# BEGIN LICENSE BLOCK
# 
# Copyright (c) 1996-2003 Jesse Vincent <jesse@bestpractical.com>
# 
# (Except where explictly superceded by other copyright notices)
# 
# This work is made available to you under the terms of Version 2 of
# the GNU General Public License. A copy of that license should have
# been provided with this software, but in any event can be snarfed
# from www.gnu.org.
# 
# This work is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# Unless otherwise specified, all modifications, corrections or
# extensions to this work which alter its source code become the
# property of Best Practical Solutions, LLC when submitted for
# inclusion in the work.
# 
# 
# END LICENSE BLOCK

# Autogenerated by DBIx::SearchBuilder factory (by <jesse@bestpractical.com>)
# WARNING: THIS FILE IS AUTOGENERATED. ALL CHANGES TO THIS FILE WILL BE LOST.  
# 
# !! DO NOT EDIT THIS FILE !!
#

use strict;


=head1 NAME

RT::QueueDeactivatedScrip


=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 METHODS

=cut

package RT::QueueDeactivatedScrip;
use RT::Record; 


use vars qw( @ISA );
@ISA= qw( RT::Record );

sub _Init {
  my $self = shift; 

  $self->Table('QueueDeactivatedScrips');
  $self->SUPER::_Init(@_);
}





=head2 Create PARAMHASH

Create takes a hash of values and creates a row in the database:

  int(11) 'QueueId'.
  int(11) 'ScripId'.
  varchar(15) 'Status' defaults to 'deactivated'.
  varchar(255) 'Description'.

=cut




sub Create {
    my $self = shift;
    my %args = ( 
                QueueId => '0',
                ScripId => '0',
                Status => 'deactivated',
                Description => '',

		  @_);
    $self->SUPER::Create(
                         QueueId => $args{'QueueId'},
                         ScripId => $args{'ScripId'},
                         Status => $args{'Status'},
                         Description => $args{'Description'},
);

}



=head2 id

Returns the current value of id. 
(In the database, id is stored as int(11).)


=cut


=head2 QueueId

Returns the current value of QueueId. 
(In the database, QueueId is stored as int(11).)



=head2 SetQueueId VALUE


Set QueueId to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, QueueId will be stored as a int(11).)


=cut


=head2 ScripId

Returns the current value of ScripId. 
(In the database, ScripId is stored as int(11).)



=head2 SetScripId VALUE


Set ScripId to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, ScripId will be stored as a int(11).)


=cut


=head2 Status

Returns the current value of Status. 
(In the database, Status is stored as varchar(15).)



=head2 SetStatus VALUE


Set Status to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Status will be stored as a varchar(15).)


=cut


=head2 Description

Returns the current value of Description. 
(In the database, Description is stored as varchar(255).)



=head2 SetDescription VALUE


Set Description to VALUE. 
Returns (1, 'Status message') on success and (0, 'Error Message') on failure.
(In the database, Description will be stored as a varchar(255).)


=cut



sub _ClassAccessible {
    {
     
        id =>
		{read => 1, type => 'int(11)', default => ''},
        QueueId => 
		{read => 1, write => 1, type => 'int(11)', default => '0'},
        ScripId => 
		{read => 1, write => 1, type => 'int(11)', default => '0'},
        Status => 
		{read => 1, write => 1, type => 'varchar(15)', default => 'deactivated'},
        Description => 
		{read => 1, write => 1, type => 'varchar(255)', default => ''},

 }
};


        eval "require RT::QueueDeactivatedScrip_Overlay";
        if ($@ && $@ !~ qr{^Can't locate RT/QueueDeactivatedScrip_Overlay.pm}) {
            die $@;
        };

        eval "require RT::QueueDeactivatedScrip_Vendor";
        if ($@ && $@ !~ qr{^Can't locate RT/QueueDeactivatedScrip_Vendor.pm}) {
            die $@;
        };

        eval "require RT::QueueDeactivatedScrip_Local";
        if ($@ && $@ !~ qr{^Can't locate RT/QueueDeactivatedScrip_Local.pm}) {
            die $@;
        };




=head1 SEE ALSO

This class allows "overlay" methods to be placed
into the following files _Overlay is for a System overlay by the original author,
_Vendor is for 3rd-party vendor add-ons, while _Local is for site-local customizations.  

These overlay files can contain new subs or subs to replace existing subs in this module.

If you'll be working with perl 5.6.0 or greater, each of these files should begin with the line 

   no warnings qw(redefine);

so that perl does not kick and scream when you redefine a subroutine or variable in your overlay.

RT::QueueDeactivatedScrip_Overlay, RT::QueueDeactivatedScrip_Vendor, RT::QueueDeactivatedScrip_Local

=cut


1;
